# Generated by Django 3.2.4 on 2021-06-26 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200, verbose_name='Название - H1')),
                ('cat_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('cat_metadesc', models.CharField(max_length=300, verbose_name='Мета описание')),
                ('cat_short_desc', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('cat_desc', models.TextField(blank=True, verbose_name='Полное описание')),
                ('cat_image', models.ImageField(upload_to='', verbose_name='Изображение категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название - H1')),
                ('product_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('product_metadesc', models.CharField(max_length=300, verbose_name='Мета описание')),
                ('product_short_desc', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('product_desc', models.TextField(blank=True, verbose_name='Полное описание')),
                ('product_image', models.ImageField(upload_to='', verbose_name='Изображение продукта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycle.category')),
            ],
        ),
    ]
