# Generated by Django 3.2.4 on 2021-06-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0003_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('kg', 'за кг'), ('cn', 'за шт')], default='green', max_length=6),
        ),
    ]
