# Generated by Django 3.2.4 on 2021-06-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0006_alter_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('килограмм', 'за кг'), ('штук', 'за шт')], default='kg', max_length=10, verbose_name='Оплата'),
        ),
    ]
