# Generated by Django 3.2.4 on 2021-07-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0007_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Килограмм', 'за кг'), ('Штук', 'за шт')], default='kg', max_length=10, verbose_name='Оплата'),
        ),
    ]
