# Generated by Django 3.2.4 on 2021-07-05 09:56

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0008_alter_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=200, verbose_name='Название - H1')),
                ('article_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('article_metadesc', models.CharField(max_length=300, verbose_name='Мета описание')),
                ('article_short_desc', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('article_image', models.ImageField(upload_to='', verbose_name='Изображение статьи')),
                ('body_editorjs', django_editorjs_fields.fields.EditorJsJSONField()),
            ],
        ),
    ]
