# Generated by Django 3.2.4 on 2021-07-05 11:28

from django.db import migrations, models
import django.db.models.deletion
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0009_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=200, verbose_name='Название региона')),
                ('region_title', models.CharField(max_length=200, verbose_name='Заголовок title')),
                ('region_metadesc', models.CharField(max_length=300, verbose_name='Описание description')),
                ('region_short_desc', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('body_editorjs', django_editorjs_fields.fields.EditorJsJSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='article_metadesc',
            field=models.CharField(max_length=300, verbose_name='Описание description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_name',
            field=models.CharField(max_length=200, verbose_name='Заголовок H1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_metadesc',
            field=models.CharField(max_length=300, verbose_name='Описание description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=200, verbose_name='Название категории продукта'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_metadesc',
            field=models.CharField(max_length=300, verbose_name='Описание description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок title'),
        ),
        migrations.CreateModel(
            name='Punkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punkt_name', models.CharField(max_length=200, verbose_name='Название пункта приема')),
                ('punkt_title', models.CharField(max_length=200, verbose_name='Заголовок title')),
                ('punkt_metadesc', models.CharField(max_length=300, verbose_name='Описание description')),
                ('punkt_short_desc', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('punkt_image', models.ImageField(upload_to='', verbose_name='Изображение пункта')),
                ('body_editorjs', django_editorjs_fields.fields.EditorJsJSONField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycle.region')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=200, verbose_name='Имя агента')),
                ('agent_title', models.CharField(max_length=200, verbose_name='Заголовок title')),
                ('agent_metadesc', models.CharField(max_length=300, verbose_name='Описание description')),
                ('agent_short_desc', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('agent_image', models.ImageField(upload_to='', verbose_name='Фото агента')),
                ('body_editorjs', django_editorjs_fields.fields.EditorJsJSONField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycle.region')),
            ],
        ),
    ]
