# Generated by Django 3.2.4 on 2021-07-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0011_category_cat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2021-07-06 15:08:57.333279', max_length=200, verbose_name='URL'),
        ),
    ]
