# Generated by Django 3.2.4 on 2021-07-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0013_auto_20210707_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2021-07-07 12:19:25.494712', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2021-07-07 12:19:25.516079', max_length=200, verbose_name='URL'),
        ),
    ]
