# Generated by Django 3.2.4 on 2021-07-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0014_auto_20210707_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='punkt',
            name='punkt_geo',
            field=models.CharField(default='55.659173,37.762848', max_length=300, verbose_name='Описание description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2021-07-07 12:51:36.444322', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2021-07-07 12:51:36.465870', max_length=200, verbose_name='URL'),
        ),
    ]
