# Generated by Django 3.2.4 on 2021-07-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0018_auto_20210707_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isStock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2021-07-08 12:00:19.396302', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2021-07-08 12:00:19.368958', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2021-07-08 12:00:19.396915', max_length=200, verbose_name='URL'),
        ),
    ]
