# Generated by Django 3.2.4 on 2021-07-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0020_auto_20210708_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2021-07-22 08:20:59.215654', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_metadesc',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2021-07-22 08:20:59.194285', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Килограмм', 'кг'), ('Штук', 'шт')], default='kg', max_length=10, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2021-07-22 08:20:59.216081', max_length=200, verbose_name='URL'),
        ),
    ]
