# Generated by Django 3.2.4 on 2021-07-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0023_auto_20210722_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2021-07-22 08:31:01.538421', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2021-07-22 08:31:01.516696', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='IMG_4280_копия.jpg', upload_to='', verbose_name='Изображение продукта'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2021-07-22 08:31:01.538864', max_length=200, verbose_name='URL'),
        ),
    ]
