# Generated by Django 3.2.4 on 2021-08-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0035_auto_20210820_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2021-08-20 14:41:10.831274', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2021-08-20 14:41:10.723584', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2021-08-20 14:41:10.832009', max_length=200, verbose_name='URL'),
        ),
    ]
