# Generated by Django 3.2.4 on 2021-08-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0037_auto_20210823_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок для Open Graph (og:title)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2021-08-23 06:10:17.450218', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок для Open Graph (og:title)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2021-08-23 06:10:17.381479', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок для Open Graph (og:title)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок для Open Graph (og:title)'),
        ),
        migrations.AlterField(
            model_name='punkt',
            name='punkt_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок для Open Graph (og:title)'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2021-08-23 06:10:17.453440', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок для Open Graph (og:title)'),
        ),
    ]
