# Generated by Django 3.2.4 on 2021-08-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0038_auto_20210823_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2021-08-23 06:11:45.044543', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2021-08-23 06:11:44.963220', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2021-08-23 06:11:45.045264', max_length=200, verbose_name='URL'),
        ),
    ]
