# Generated by Django 3.2.4 on 2022-02-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0039_auto_20210823_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test_row',
            field=models.TextField(blank=True, verbose_name='Тест'),
        ),
    ]
