# Generated by Django 3.0 on 2022-02-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0043_auto_20220206_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test_row',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2022-02-06 21:04:14.020694', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2022-02-06 21:04:13.990634', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2022-02-06 21:04:14.021451', max_length=200, verbose_name='URL'),
        ),
    ]
