# Generated by Django 2.2 on 2022-02-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0045_auto_20220206_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2022-02-06 21:13:41.340896', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2022-02-06 21:13:41.312125', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2022-02-06 21:13:41.341735', max_length=200, verbose_name='URL'),
        ),
    ]
