# Generated by Django 2.2 on 2022-02-06 21:14

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0046_auto_20220206_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='test_artictle',
            field=django_editorjs_fields.fields.EditorJsTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2022-02-06 21:14:47.005108', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2022-02-06 21:14:46.978344', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2022-02-06 21:14:47.005958', max_length=200, verbose_name='URL'),
        ),
    ]
