# Generated by Django 2.2 on 2022-02-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0047_auto_20220206_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='test_artictle',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2022-02-06 21:15:35.038961', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2022-02-06 21:15:35.009871', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2022-02-06 21:15:35.039832', max_length=200, verbose_name='URL'),
        ),
    ]
