# Generated by Django 2.2 on 2022-02-06 21:27

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0049_auto_20220206_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2022-02-06 21:27:37.323532', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2022-02-06 21:27:37.292063', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2022-02-06 21:27:37.324255', max_length=200, verbose_name='URL'),
        ),
    ]
