# Generated by Django 2.2 on 2022-02-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0052_auto_20220206_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2022-02-09 08:24:08.360672', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2022-02-09 08:24:08.361549', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2022-02-09 08:24:08.281432', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2022-02-09 08:24:08.362264', max_length=200, verbose_name='URL'),
        ),
    ]
