# Generated by Django 2.2 on 2022-07-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0057_auto_20220721_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2022-07-21 18:46:30.333038', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2022-07-21 18:46:30.297318', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2022-07-21 18:46:30.332203', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2022-07-21 18:46:30.333714', max_length=200, verbose_name='URL'),
        ),
    ]
