# Generated by Django 2.2 on 2022-08-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0058_auto_20220721_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_questions_and_answer',
            field=models.TextField(blank=True, verbose_name='Впоросы и ответы'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2022-08-14 16:41:26.230344', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2022-08-14 16:41:26.150461', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2022-08-14 16:41:26.229482', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2022-08-14 16:41:26.231113', max_length=200, verbose_name='URL'),
        ),
    ]
