# Generated by Django 2.2 on 2022-08-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0059_auto_20220814_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_questions_and_answer',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_answer_1',
            field=models.TextField(blank=True, default='', verbose_name='Ответ 1'),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_answer_2',
            field=models.TextField(blank=True, default='', verbose_name='Ответ 2'),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_question_1',
            field=models.TextField(blank=True, default='', verbose_name='Вопрос 1'),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_question_2',
            field=models.TextField(blank=True, default='', verbose_name='Вопорос 2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2022-08-14 18:24:53.401303', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2022-08-14 18:24:53.372021', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2022-08-14 18:24:53.400489', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2022-08-14 18:24:53.401949', max_length=200, verbose_name='URL'),
        ),
    ]
