# Generated by Django 2.2 on 2022-09-05 15:58

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0060_auto_20220814_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_answer_3',
            field=django_editorjs_fields.fields.EditorJsJSONField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_question_3',
            field=models.TextField(blank=True, default='', verbose_name='Вопрос 3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2022-09-05 18:58:42.699756', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2022-09-05 18:58:42.669621', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2022-09-05 18:58:42.698872', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2022-09-05 18:58:42.700463', max_length=200, verbose_name='URL'),
        ),
    ]
