# Generated by Django 2.2 on 2022-09-05 16:35

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0061_auto_20220905_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_answer_4',
            field=django_editorjs_fields.fields.EditorJsJSONField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_answer_5',
            field=django_editorjs_fields.fields.EditorJsJSONField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_question_4',
            field=models.TextField(blank=True, default='', verbose_name='Вопрос 3'),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_question_5',
            field=models.TextField(blank=True, default='', verbose_name='Вопрос 3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2022-09-05 19:35:06.953956', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_answer_1',
            field=django_editorjs_fields.fields.EditorJsJSONField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_answer_2',
            field=django_editorjs_fields.fields.EditorJsJSONField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2022-09-05 19:35:06.916915', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2022-09-05 19:35:06.953147', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2022-09-05 19:35:06.954711', max_length=200, verbose_name='URL'),
        ),
    ]
