# Generated by Django 2.2 on 2022-09-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0062_auto_20220905_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2022-09-05 19:37:23.626116', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_question_4',
            field=models.TextField(blank=True, default='', verbose_name='Вопрос 4'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_question_5',
            field=models.TextField(blank=True, default='', verbose_name='Вопрос 5'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2022-09-05 19:37:23.595691', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2022-09-05 19:37:23.625292', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2022-09-05 19:37:23.626815', max_length=200, verbose_name='URL'),
        ),
    ]
