# Generated by Django 2.2 on 2022-09-05 16:43

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0063_auto_20220905_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2022-09-05 19:43:08.831189', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_answer_1',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_answer_2',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_answer_3',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_answer_4',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_answer_5',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2022-09-05 19:43:08.798667', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2022-09-05 19:43:08.830385', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2022-09-05 19:43:08.831947', max_length=200, verbose_name='URL'),
        ),
    ]
