# Generated by Django 3.2.4 on 2023-02-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0002_auto_20230220_1315'),
        ('recycle', '0065_auto_20220905_1949'),
    ]

    operations = [
    ]
