# Generated by Django 3.2.4 on 2023-02-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0066_merge_0002_auto_20230220_1315_0065_auto_20220905_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='body_editorjs',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body_editorjs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='body_editorjs',
        ),
        migrations.RemoveField(
            model_name='punkt',
            name='body_editorjs',
        ),
        migrations.RemoveField(
            model_name='region',
            name='body_editorjs',
        ),
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2023-02-20 15:43:37.632821', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2023-02-20 15:43:37.599272', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2023-02-20 15:43:37.632821', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='punkt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2023-02-20 15:43:37.632821', max_length=200, verbose_name='URL'),
        ),
    ]
