# Generated by Django 3.2.4 on 2023-02-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0067_auto_20230220_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_answer_1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_answer_2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_answer_3',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_answer_4',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_answer_5',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_question_1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_question_2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_question_3',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_question_4',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_question_5',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2023-02-20 15:43:59.797111', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2023-02-20 15:43:59.761894', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2023-02-20 15:43:59.796111', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2023-02-20 15:43:59.797111', max_length=200, verbose_name='URL'),
        ),
    ]
