# Generated by Django 3.2.4 on 2023-02-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0069_auto_20230220_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='punkt',
            name='punkt_negative',
            field=models.IntegerField(blank=True, default=0, verbose_name='Негативный рейтинг'),
        ),
        migrations.AddField(
            model_name='punkt',
            name='punkt_positive',
            field=models.IntegerField(blank=True, default=0, verbose_name='Позитивный рейтинг'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2023-02-20 15:48:17.748636', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2023-02-20 15:48:17.713709', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2023-02-20 15:48:17.747641', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2023-02-20 15:48:17.748636', max_length=200, verbose_name='URL'),
        ),
    ]
